num_shot: 3
device: 'cuda:1'
dataset:
  name: 'chameleon'
model:
  hidden_dim: 128
  backbone: 'GCN'
  pretrain_type: 'dagprompt'
  prompt_type: 'dagprompt'
  num_layers: 3
  alpha: 0.9
optim:
  batch_size: 1000000
  lr: 1e-3
  wd: 2.5e-6
