# 58.29 | std 2.12
num_shot: 10
device: 'cuda:1'
dataset:
  name: 'chameleon'

model:
  hidden_dim: 256
  backbone: 'GCN'
  pretrain_type: 'dagprompt'
  prompt_type: 'dagprompt'
  num_layers: 4
  alpha: 0.3
optim:
  batch_size: 1000000
  lr: 1e-3
  wd: 0.0